#!/bin/bash
# Script: generate-example-output.sh
# Description: Generate example output files for llm-d-modelservice


set -e

# Common function to generate output files
generate_output() {
	local release_name="$1"
	local values_file="$2"
	local output_file="$3"
	local set_args="$4"
	helm template "$release_name" charts/llm-d-modelservice/ -f "$values_file" $set_args \
		| sed '1s/^/# generated by generate-example-output.sh\n/' > "$output_file"
	echo "Generated: $output_file"
}

# Generate output-cpu.yaml (Simulated CPU deployment)
generate_output "cpu-sim" "examples/values-cpu.yaml" "examples/output-cpu.yaml"

# Generate output-dra.yaml (Dynamic Resource Allocation deployment for Intel B50 GPU device)
generate_output "dra" "examples/values-dra.yaml" "examples/output-dra.yaml" '--set modelArtifacts.uri=pvc+hf://model-pvc/meta-llama/Llama-3.1-8B-Instruct'

# Generate output-gaudi.yaml (Intel Gaudi)
generate_output "gaudi" "examples/values-gaudi.yaml" "examples/output-gaudi.yaml"

# Generate output-pd.yaml (PD deployment)
generate_output "pd" "examples/values-pd.yaml" "examples/output-pd.yaml"

# Generate output-heterogeneous-pd.yaml (Heterogeneous accelerator P/D deployment)
generate_output "heterogeneous-pd" "examples/values-heterogeneous-pd.yaml" "examples/output-heterogeneous-pd.yaml"

# Generate output-pd-mnnvl.yaml (PD deployment with Multi Node NVLink)
generate_output "pd-mnnvl" "examples/values-pd-mnnvl.yaml" "examples/output-pd-mnnvl.yaml"

# Generate output-xpu-pd.yaml (Intel i915)
generate_output "xpu-pd" "examples/values-xpu-pd.yaml" "examples/output-xpu-pd.yaml"

# Generate output-xpu.yaml (Intel Xe GPU and affinity)
generate_output "xpu" "examples/values-xpu.yaml" "examples/output-xpu.yaml"

# Generate output-requester.yaml (Requester deployment)
generate_output "requester" "examples/values-requester.yaml" "examples/output-requester.yaml"

# Generate output-pvc.yaml (PVC model deployment)
generate_output "pvc" "examples/values-pd.yaml" "examples/output-pvc.yaml" '--set modelArtifacts.uri=pvc://pvc-name/path/to/model'

# Generate output-pvc-hf.yaml (PVC HuggingFace model deployment)
generate_output "pvc-hf" "examples/values-pd.yaml" "examples/output-pvc-hf.yaml" '--set modelArtifacts.uri=pvc+hf://pvc-name/path/to/hf_hub_cache/facebook/opt-125m'

# Generate output-rebellions-atom.yaml (Rebellions ATOM deployment)
generate_output "rebellions-atom" "examples/values-rebellions-atom.yaml" "examples/output-rebellions-atom.yaml"
