---
# Source: llm-d-modelservice/templates/epp-sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: facebook-llm-d-modelservice-epp
  labels:
    helm.sh/chart: llm-d-modelservice-0.0.8
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
---
# Source: llm-d-modelservice/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: facebook-llm-d-modelservice
  labels:
    helm.sh/chart: llm-d-modelservice-0.0.8
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
---
# Source: llm-d-modelservice/templates/epp-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: facebook-llm-d-modelservice-epp
rules:
- apiGroups:
  - inference.networking.x-k8s.io
  resources:
  - inferencemodels
  - inferencepools
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
# Source: llm-d-modelservice/templates/epp-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: facebook-llm-d-modelservice-epp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: facebook-llm-d-modelservice-epp
subjects:
- kind: ServiceAccount
  name: facebook-llm-d-modelservice-epp
---
# Source: llm-d-modelservice/templates/epp-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: facebook-llm-d-modelservice-epp
  labels:
    helm.sh/chart: llm-d-modelservice-0.0.8
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 9002
      targetPort: 9002
      protocol: TCP
      appProtocol: http2
  selector:
    llm-d.ai/epp: facebook-llm-d-modelservice-epp
---
# Source: llm-d-modelservice/templates/decode-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: facebook-llm-d-modelservice-decode
  labels:
    helm.sh/chart: llm-d-modelservice-0.0.8
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      llm-d.ai/inferenceServing: "true"
      llm-d.ai/model: facebook-llm-d-modelservice
      llm-d.ai/role: decode
  template:
    metadata:
      labels:
        llm-d.ai/inferenceServing: "true"
        llm-d.ai/model: facebook-llm-d-modelservice
        llm-d.ai/role: decode
    spec:
      initContainers:
        - name: routing-proxy
          args:
            - --port=8000
            - --vllm-port=8200
            - --connector=nixlv2
            - -v=5
          image: ghcr.io/llm-d/llm-d-routing-sidecar:0.0.6
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources: {}
          restartPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
    
      serviceAccountName: facebook-llm-d-modelservice
      volumes:
        - name: model-storage
          emptyDir: 
            sizeLimit: 20Gi
      containers:
        - name: vllm
          image: ghcr.io/llm-d/llm-d:0.0.8
          
          command: ["vllm", "serve"]
          args:
            - "facebook/opt-125m"
            - --port
            - "8200"
            
            - --enforce-eager
            - --kv-transfer-config
            - '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}'
          env:
          - name: CUDA_VISIBLE_DEVICES
            value: "0"
          - name: UCX_TLS
            value: cuda_ipc,cuda_copy,tcp
          - name: VLLM_NIXL_SIDE_CHANNEL_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: VLLM_NIXL_SIDE_CHANNEL_PORT
            value: "5557"
          - name: VLLM_LOGGING_LEVEL
            value: DEBUG
          - name: DP_SIZE
            value: "1"
          - name: TP_SIZE
            value: "1"
          - name: DP_SIZE_LOCAL
            value: "1"
          - name: HF_HOME
            value: /model-cache
          
          resources:
            limits:
              cpu: "16"
              memory: 16Gi
              nvidia.com/gpu: "1"
            requests:
              cpu: "16"
              memory: 16Gi
              nvidia.com/gpu: "1"
          volumeMounts:
          - name: model-storage
            mountPath: /model-cache
---
# Source: llm-d-modelservice/templates/epp-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: facebook-llm-d-modelservice-epp
  labels:
    llm-d.ai/epp: facebook-llm-d-modelservice-epp
  namespace: e2e-solution
spec:
  replicas: 1
  selector:
    matchLabels:
      llm-d.ai/epp: facebook-llm-d-modelservice-epp
  template:
    metadata:
      labels:
        llm-d.ai/epp: facebook-llm-d-modelservice-epp
    spec:
      containers:
      - name: epp
        imagePullPolicy: Always
        image: ghcr.io/llm-d/llm-d-inference-scheduler:0.0.3
        args:
        - --poolName
        - facebook-llm-d-modelservice
        - --poolNamespace
        - e2e-solution
        - -v
        - "4"
        - --zap-encoder
        - json
        - --grpcPort
        - "9002"
        - --grpcHealthPort
        - "9003"
        env:
        - name: ENABLE_KVCACHE_AWARE_SCORER
          value: "false"
        - name: ENABLE_LOAD_AWARE_SCORER
          value: "true"
        - name: ENABLE_PREFIX_AWARE_SCORER
          value: "true"
        - name: ENABLE_SESSION_AWARE_SCORER
          value: "false"
        - name: KVCACHE_AWARE_SCORER_WEIGHT
          value: "1"
        - name: KVCACHE_INDEXER_REDIS_ADDR
        - name: LOAD_AWARE_SCORER_WEIGHT
          value: "1"
        - name: PD_ENABLED
          value: "false"
        - name: PD_PROMPT_LEN_THRESHOLD
          value: "10"
        - name: PREFILL_ENABLE_KVCACHE_AWARE_SCORER
          value: "false"
        - name: PREFILL_ENABLE_LOAD_AWARE_SCORER
          value: "false"
        - name: PREFILL_ENABLE_PREFIX_AWARE_SCORER
          value: "false"
        - name: PREFILL_ENABLE_SESSION_AWARE_SCORER
          value: "false"
        - name: PREFILL_KVCACHE_AWARE_SCORER_WEIGHT
          value: "1"
        - name: PREFILL_KVCACHE_INDEXER_REDIS_ADDR
        - name: PREFILL_LOAD_AWARE_SCORER_WEIGHT
          value: "1"
        - name: PREFILL_PREFIX_AWARE_SCORER_WEIGHT
          value: "1"
        - name: PREFILL_SESSION_AWARE_SCORER_WEIGHT
          value: "1"
        - name: PREFIX_AWARE_SCORER_WEIGHT
          value: "2"
        - name: SESSION_AWARE_SCORER_WEIGHT
          value: "1"
        ports:
        - containerPort: 9002
          name: grpc
          protocol: TCP
        - containerPort: 9003
          name: grpc-health
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        readinessProbe:
          grpc:
            port: 9003
            service: envoy.service.ext_proc.v3.ExternalProcessor
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          grpc:
            port: 9003
            service: envoy.service.ext_proc.v3.ExternalProcessor
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
      serviceAccount: facebook-llm-d-modelservice-epp
      serviceAccountName: facebook-llm-d-modelservice-epp
---
# Source: llm-d-modelservice/templates/prefill-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: facebook-llm-d-modelservice-prefill
  labels:
    helm.sh/chart: llm-d-modelservice-0.0.8
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      llm-d.ai/inferenceServing: "true"
      llm-d.ai/model: facebook-llm-d-modelservice
      llm-d.ai/role: prefill
  template:
    metadata:
      labels:
        llm-d.ai/inferenceServing: "true"
        llm-d.ai/model: facebook-llm-d-modelservice
        llm-d.ai/role: prefill
    spec:
    
      serviceAccountName: facebook-llm-d-modelservice
      volumes:
        - name: model-storage
          emptyDir: 
            sizeLimit: 20Gi
      containers:
        - name: vllm
          image: ghcr.io/llm-d/llm-d:0.0.8
          
          command: ["vllm", "serve"]
          args:
            - "facebook/opt-125m"
            - --port
            - "8000"
            
            - --enforce-eager
            - --kv-transfer-config
            - '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}'
          env:
          - name: CUDA_VISIBLE_DEVICES
            value: "0"
          - name: UCX_TLS
            value: cuda_ipc,cuda_copy,tcp
          - name: VLLM_NIXL_SIDE_CHANNEL_PORT
            value: "5557"
          - name: VLLM_NIXL_SIDE_CHANNEL_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: VLLM_LOGGING_LEVEL
            value: DEBUG
          - name: DP_SIZE
            value: "1"
          - name: TP_SIZE
            value: "1"
          - name: DP_SIZE_LOCAL
            value: "1"
          
          resources:
            limits:
              cpu: "16"
              memory: 16Gi
              nvidia.com/gpu: "1"
            requests:
              cpu: "16"
              memory: 16Gi
              nvidia.com/gpu: "1"
---
# Source: llm-d-modelservice/templates/httproute.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: facebook-llm-d-modelservice
  namespace: e2e-solution
  labels:
    helm.sh/chart: llm-d-modelservice-0.0.8
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: inference-gateway
  rules:
  - backendRefs:
    - group: inference.networking.x-k8s.io
      kind: InferencePool
      name: facebook-llm-d-modelservice
      port: 8000
      weight: 1
    matches:
    - headers:
      - name: x-model-name
        type: Exact
        value: facebook/opt-125m
      path:
        type: PathPrefix
        value: /
---
# Source: llm-d-modelservice/templates/inferencepool.yaml
apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferencePool
metadata:
  name: facebook-llm-d-modelservice
  namespace: e2e-solution
spec:
  extensionRef:
    failureMode: FailClose
    group: ""
    kind: Service
    name: facebook-llm-d-modelservice-epp
  selector:
    llm-d.ai/inferenceServing: "true"
    llm-d.ai/model: facebook-llm-d-modelservice
  targetPortNumber: 8000
